apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: api-notifications-deployment # Nombre del deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-notifications # Match label para agrupar contenedores
  template:
    metadata:
      labels:
        app: api-notifications # Nombre Pod
    spec:
      containers:
      - name: api-notifications # Nombre del contenedor
        image: gcr.io/{GOOGLE_PROJECT_ID}/{IMAGE_DOCKER}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: MANAGER_AUTH_TOKEN
          value: "1"
        - name: SALESFORCE_MAIL_URL
          value: "2"
        - name: SALESFORCE_TOKEN_URL
          value: "3"
        - name: SALESFORCE_TOKEN_CLIENT_CREDENTIALS
          value: "4"
        - name: SALESFORCE_TOKEN_CLIENT_ID
          value: "5"
        - name: SALESFORCE_TOKEN_CLIENT_SECRET
          value: "6"
        - name: SALESFORCE_TOKEN_SCOPE
          value: "7"
        - name: SALESFORCE_TOKEN_ACCOUNT_ID
          value: "8"
        - name: SALESFORCE_ENCRYT_WORDKEY
          value: "9"
      imagePullSecrets:
      - name: gcrsecret # Secrets que contiene la cuenta de servicio para realizar pull de repositorio de Images Mallplaza
